DEMO_SCENARIOS = {
    1: {
        "name": "Genuine Passenger",
        "ocr_confidence": 0.974,
        "mrz_ok": True,
        "tampering": False,
        "face_score": 0.967,
        "face_liveness": "PASS",
        "face_pad": "PASS",
        "fingerprint_score": 0.988,
        "fingerprint_pad": "PASS",
        "iris_score": 0.991,
        "iris_pad": "PASS",
        "expected_risk": 8,
        "expected_status": "VERIFIED"
    },
    2: {
        "name": "Document Tampering",
        "ocr_confidence": 0.892,
        "mrz_ok": True,
        "tampering": True,
        "face_score": 0.941,
        "face_liveness": "PASS",
        "face_pad": "PASS",
        "fingerprint_score": 0.977,
        "fingerprint_pad": "PASS",
        "iris_score": 0.983,
        "iris_pad": "PASS",
        "expected_risk": 52,
        "expected_status": "REVIEW_REQUIRED"
    },
    3: {
        "name": "Possible Impersonation",
        "ocr_confidence": 0.961,
        "mrz_ok": True,
        "tampering": False,
        "face_score": 0.512,
        "face_liveness": "PASS",
        "face_pad": "PASS",
        "fingerprint_score": 0.981,
        "fingerprint_pad": "PASS",
        "iris_score": 0.979,
        "iris_pad": "PASS",
        "expected_risk": 68,
        "expected_status": "REVIEW_REQUIRED"
    },
    4: {
        "name": "Expired Visa",
        "ocr_confidence": 0.968,
        "mrz_ok": True,
        "tampering": False,
        "face_score": 0.951,
        "face_liveness": "PASS",
        "face_pad": "PASS",
        "fingerprint_score": 0.974,
        "fingerprint_pad": "PASS",
        "iris_score": 0.988,
        "iris_pad": "PASS",
        "visa_expired": True,
        "expected_risk": 45,
        "expected_status": "REVIEW_REQUIRED"
    },
    5: {
        "name": "Multiple Conflicts",
        "ocr_confidence": 0.71,
        "mrz_ok": False,
        "tampering": True,
        "face_score": 0.412,
        "face_liveness": "PASS",
        "face_pad": "PASS",
        "fingerprint_score": 0.621,
        "fingerprint_pad": "UNCERTAIN",
        "iris_score": 0.381,
        "iris_pad": "PASS",
        "expected_risk": 91,
        "expected_status": "HIGH_RISK"
    }
}
